name: hng14-stage2-devops-main

services:

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--port", "6379"]
    networks:
      - app_network

    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6379", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "128m"

  backend:
    build:
      context: .
      dockerfile: api/Dockerfile

    restart: unless-stopped
    networks:
      - app_network

    environment:
      BACKEND_PORT: "8000"
      REDIS_HOST: redis
      REDIS_PORT: "6379"

    depends_on:
      redis:
        condition: service_healthy

    ports:
      - "8000:8000"

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256m"

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile

    restart: unless-stopped
    networks:
      - app_network

    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"

    depends_on:
      redis:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "pgrep", "-f", "worker.py"]
      interval: 5s
      timeout: 3s
      retries: 5

    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256m"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile

    restart: unless-stopped
    networks:
      - app_network

    environment:
      API_URL: http://backend:8000
      FRONTEND_PORT: "3000"

    depends_on:
      backend:
        condition: service_healthy

    ports:
      - "3000:3000"

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5

    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "128m"

networks:
  app_network:
    driver: bridge